name: Deploy Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SCRIPT_ID: "1eKtnybTCz-GKohMdtdEKVDBUzFK3suniSAT0UDEKsM_Fm5dR9aRMs3WN"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'

      - name: Install dependencies
        run: |
          npm install -g @google/clasp
          npm install

      - name: Set up .clasp.json file
        run: |
          echo '{"scriptId":"${{ env.SCRIPT_ID }}","rootDir":"dist"}' > $GITHUB_WORKSPACE/.clasp.json

      - name: Set up OAuth credentials
        run: |
          echo "${{ secrets.CLASPRC_ETHGLOBAL }}" | base64 -d > ~/.clasprc.json
          echo "${{ secrets.CLASPRC_ETHGLOBAL }}" | base64 -d > $GITHUB_WORKSPACE/.clasprc.json

      - name: Build the latest
        run: npm run build

      - name: Deploy ethglobal
        run: |
          echo "Deploying ethglobal..."
          cd $GITHUB_WORKSPACE
          clasp push -f && echo "Deploying ethglobal... done."
